/*
 * Copyright 2022 Bytedance Inc.
 * SPDX license identifier: LGPL-2.1-or-later
 */

#ifndef AVCODEC_BYTEVC2_H
#define AVCODEC_BYTEVC2_H

enum BYTEVC2NALUnitType {
    BYTEVC2_NAL_TYPE_0 = 10,
    BYTEVC2_NAL_TYPE_1 = 14,
    BYTEVC2_NAL_TYPE_2 = 15,
    BYTEVC2_NAL_TYPE_3 = 16,
    BYTEVC2_NAL_TYPE_4 = 17,
    BYTEVC2_NAL_TYPE_5 = 18,
    BYTEVC2_NAL_TYPE_6 = 19,
    BYTEVC2_NAL_TYPE_7 = 23,
    BYTEVC2_NAL_TYPE_8 = 24,
    BYTEVC2_NAL_TYPE_9 = 29,
    BYTEVC2_NAL_TYPE_10 = 30,
    BYTEVC2_NAL_TYPE_11 = 31,
};

#define BYTEVC2_MAX_SUB_LAYERS 7
#define BYTEVC2_MAX_SHORT_TERM_RPS_COUNT 64
#define BYTEVC2_MAX_LADF_INTERVALS 5
#define BYTEVC2_SCALING_LIST_REM_NUM 6
#define BYTEVC2_SCALING_LIST_NUM (3*(4-2))

#endif /* AVCODEC_BYTEVC2_H */